### ISSUE TITLE
Features of New Version - To-Do-List

### ISSUE THREAD

**Issue by Seth0x41** [Seth0x41/Thoth#2]
- [x] Build flask Application to manage and monitor Chatbot.
- [x] Transforming chatbot handle methods to inline keyboards.
- [x] Categorize courses depending on the selected department.
- [x] Notify All users at chatbot.
- [x] User Ability to Add additional Courses.
- [x] Automatically Levelup after passing user.
- [x] Changing project Structure.
- [ ] Add .confing file.
